CREATE TABLE public.logs (
	"data" bytea NOT NULL,
	"index" int4 NOT NULL,
	first_topic bytea NULL,
	second_topic bytea NULL,
	third_topic bytea NULL,
	fourth_topic bytea NULL,
	inserted_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	address_hash bytea NULL,
	transaction_hash bytea NOT NULL,
	block_hash bytea NOT NULL,
	block_number int4 NULL,
);

CREATE TABLE public.pending_block_operations (
	block_hash bytea NOT NULL,
	inserted_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	block_number int4 NULL,
);

CREATE TABLE public.smart_contracts (
	id bigserial NOT NULL,
	"name" varchar(255) NOT NULL,
	compiler_version varchar(255) NOT NULL,
	optimization bool NOT NULL,
	contract_source_code text NOT NULL,
	abi jsonb NULL,
	address_hash bytea NOT NULL,
	inserted_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	constructor_arguments text NULL,
	optimization_runs int8 NULL,
	evm_version varchar(255) NULL,
	external_libraries _jsonb DEFAULT ARRAY[]::jsonb[] NULL,
	verified_via_sourcify bool NULL,
	is_vyper_contract bool NULL,
	partially_verified bool NULL,
	file_path text NULL,
	is_changed_bytecode bool DEFAULT false NULL,
	bytecode_checked_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) - '1 day'::interval NULL,
	contract_code_md5 varchar(255) NOT NULL,
	compiler_settings jsonb NULL,
	verified_via_eth_bytecode_db bool NULL,
	license_type int2 DEFAULT 1 NOT NULL,
	verified_via_verifier_alliance bool NULL,
	certified bool NULL,
	is_blueprint bool NULL,
);

CREATE TABLE public.token_transfers (
	transaction_hash bytea NOT NULL,
	log_index int4 NOT NULL,
	from_address_hash bytea NOT NULL,
	to_address_hash bytea NOT NULL,
	amount numeric NULL,
	token_contract_address_hash bytea NOT NULL,
	inserted_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	block_number int4 NULL,
	block_hash bytea NOT NULL,
	amounts _numeric NULL,
	token_ids _numeric NULL,
	token_type varchar(255) NULL,
	block_consensus bool DEFAULT true NULL,
);

CREATE TABLE public.tokens (
	"name" text NULL,
	symbol text NULL,
	total_supply numeric NULL,
	decimals numeric NULL,
	"type" varchar(255) NOT NULL,
	cataloged bool DEFAULT false NULL,
	contract_address_hash bytea NOT NULL,
	inserted_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	holder_count int4 NULL,
	skip_metadata bool NULL,
	fiat_value numeric NULL,
	circulating_market_cap numeric NULL,
	total_supply_updated_at_block int8 NULL,
	icon_url varchar(255) NULL,
	is_verified_via_admin_panel bool DEFAULT false NULL,
	volume_24h numeric NULL,
);

